financeiro/urls.py
__author__ = 'rafael'
from django.conf.urls import url

urlpatterns = [
    url(r'^recebe_fatura/$', 'financeiro.views.recebe_fatura', name="recebe_fatura"),
]

real_estate/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from advertiser.models import Account
from django.utils.text import slugify

TRANSACAO = (
    ('V', 'Venda'),
    ('L', 'Locação')
)

LOGTYPE = (
    ('A', 'Acesso'),
    ('T', 'Telefone'),
    ('C', 'Contato')
)


class Categoria(models.Model):
    nome = models.CharField(max_length=255, null=False, blank=False)
    slug = models.SlugField(unique=True, blank=True, null=True)
    pai = models.ForeignKey('self')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nome)
        super(Categoria, self).save(*args, **kwargs)

    def __str__(self):
        return self.nome


class Propriedade(models.Model):
    account = models.ForeignKey(Account)
    referer = models.CharField(max_length=70, null=False, blank=False)
    transacao = models.CharField(max_length=1, null=False, blank=False, choices=TRANSACAO)
    categoria = models.ForeignKey(Categoria, null=True, blank=True)
    valor_venda = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=15)
    valor_aluguel = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=15)
    area_privada = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=15)
    area_total = models.DecimalField(null=True, blank=True, decimal_places=2, max_digits=15)
    quartos = models.IntegerField(null=True, blank=True)
    suites = models.IntegerField(null=True, blank=True)
    banheiros = models.IntegerField(null=True, blank=True)
    vagas = models.IntegerField(null=True, blank=True)
    descricao = models.TextField(null=True, blank=True)
    titulo = models.TextField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True, default=None)
    longitude = models.FloatField(null=True, blank=True, default=None)
    deletado = models.DateField(null=True, blank=True, default=None)

    endereco = models.CharField(max_length=500, blank=True, null=True)
    complemento = models.CharField(max_length=500, blank=True, null=True)
    numero = models.CharField(max_length=500, blank=True, null=True)


class FotoQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(deletado__isnull=True)


class FotoManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return FotoQuerySet(self.model)

    def get_active(self, *args, **kwargs):
        return self.get_queryset().active(*args, **kwargs)


class Fotos(models.Model):
    url = models.TextField(null=False, blank=False)
    url_aws = models.TextField(blank=True, null=True, default=None)
    posicao = models.IntegerField(blank=True, null=True, default=None)
    deletado = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    propriedade = models.ForeignKey(Propriedade)
    objects = FotoManager()

    def __str__(self):
        return self.url_aws if self.url_aws else self.url


class Log(models.Model):
    propriedade = models.ForeignKey(Propriedade)
    type = models.CharField(max_length=1, choices=LOGTYPE)
    cadastro = models.DateField(auto_now_add=True)

real_estate/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from real_estate.models import Propriedade


class PropriedadeForm(forms.ModelForm):
    titulo = forms.CharField()

    class Meta:
        model = Propriedade
        fields = ['referer', 'transacao', 'categoria', 'valor_venda', 'valor_aluguel', 'area_privada', 'area_total',
                  'quartos', 'suites', 'banheiros', 'vagas', 'descricao', 'titulo', 'latitude', 'longitude',
                  'endereco', 'complemento', 'numero']

real_estate/views.py
__author__ = 'rafael'
from django.shortcuts import render
from real_estate.models import Propriedade, Log
from advertiser.forms import ContatoForm


def listing(request, id, name):
    return render(request, 'listing.html', {})


def listing_map(request, id, name):
    return render(request, 'listing_map.html', {})


def propriedade(request, id):
    propriedade = Propriedade.objects.get(pk=id)
    Log(propriedade=propriedade, type='A').save()
    form = ContatoForm(initial={'mensagem': 'Tenho interesse neste imovel (Ref.:' + propriedade.referer + ') que encontrei no Placavirtual.com.br. Aguardo o contato. Obrigado'})

    return render(request, 'propriedade.html', {
        'real_estate': propriedade,
        'form': form
    })

real_estate/templates/propriedade.html
{% extends 'layout.html' %}
{% load staticfiles humanize widget_tweaks %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/page/mobile/geral.css' %}"/>
    <link rel="stylesheet" href="{% static 'js/plugins/owl.carousel/owl-carousel/owl.carousel.css' %}"/>
    <link rel="stylesheet" href="{% static 'js/plugins/owl.carousel/owl-carousel/owl.theme.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/page/real_estate/mobile/propriedade.css' %}"/>
{% endblock %}

{% block js %}
    <script async src="{% static 'js/plugins/owl.carousel/owl-carousel/owl.carousel.min.js' %}"></script>
    <script async src="{% static 'js/page/real_estate/propriedade.js' %}"></script>
    <script async src="{% static 'js/page/geral.js' %}"></script>
{% endblock %}

{% block container %}
    <section class="container-fluid">
        <div class="row">
            <ul class="list-unstyled col-xs-12 no-padding owl-carousel">
                {% for photo in real_estate.fotos_set.get_active %}
                    <li class="item"><img src="{{ photo }}" class="lazyOwl"/></li>
                {% endfor %}
            </ul>

            {% if real_estate.transacao == 'V' %}
                <h1 class="venda"><span>Venda</span></h1>
            {% elif real_estate.transacao == 'L' %}
                <h1 class="aluguel"><span>Aluga</span></h1>
            {% endif %}

            <h2 class="price roxo">
                R$
                {% if real_estate.transacao == 'V' %}
                    {{ real_estate.valor_venda|floatformat:"0"|intcomma }}
                {% elif real_estate.transacao == 'L' %}
                    {{ real_estate.valor_aluguel|floatformat:"0"|intcomma }}
                {% endif %}
            </h2>

            <div id="dados-imovel" class="col-xs-12 no-padding">
                <ul class="list-unstyled list-inline caracteristicas col-lg-12 col-sm-12 col-xs-12">
                    <li><h3>Priv.</h3>{% firstof real_estate.area_privada|floatformat:"0"|intcomma '--' %}</li>
                    <li><h3>Total</h3>{% firstof real_estate.area_total|floatformat:"0"|intcomma '--' %}</li>
                    <li><h3>Quartos</h3>{% firstof real_estate.quartos '--' %}</li>
                    <li><h3>Suites</h3>{% firstof real_estate.suites '--' %}</li>
                    <li><h3>Vagas</h3>{% firstof real_estate.vagas '--' %}</li>
                </ul>
                <hr class="col-xs-12 no-padding"/>
                <div class="col-xs-12 text-center" id="logo">
                    <img src="https://anunciantes.s3.amazonaws.com/avatar/788/logo.jpg" alt="" class="img-responsive"/>
                </div>
            </div>


            <form action="{% url 'contato' %}" method="post" class="col-xs-12 ajax">{% csrf_token %}
                <h3 class="col-xs-12 text-center white">Deseja mais informações deste imóvel?</h3>
                <div class="col-xs-12">
                    <div class="form-group">
                        {% render_field form.nome class="form-control f-z-20" placeholder='Digite seu nome' %}
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        {% render_field form.email class="form-control f-z-20" placeholder='Digite seu e-mail' %}
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        {% render_field form.telefone class="form-control f-z-20" placeholder='Digite seu telefone' %}
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        {% render_field form.mensagem class="form-control f-z-20" placeholder='Digite sua mensagem'%}
                    </div>
                </div>
                <div class="form-actions text-center">
                    <input type="hidden" name="account" value="{{ real_estate.account.pk }}"/>
                    <input type='hidden' name="propriedade" value="{{ real_estate.pk }}" />
                    <button class="btn btn-roxo bold input-lg" type="submit" tabindex="14">Enviar</button>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

real_estate/templates/unique.html
{% load staticfiles humanize real_estate_filter %}
<link rel="stylesheet" href="{% static 'css/page/real_estate/mobile/unique.css' %}"/>
<a href="{% url 'propriedade' id=real_estate.pk %}" class="unique col-lg-12 col-xs-12 no-padding">

    {% if real_estate.transacao == 'V' %}
        <h1 class="venda"><span>Venda</span></h1>
    {% elif real_estate.transacao == 'L' %}
        <h1 class="aluguel"><span>Aluga</span></h1>
    {% endif %}

    <ul class="list-unstyled">
        {% for photo in real_estate.photo|slice:'1' %}
            <li>
                <img src="{{ photo }}" alt="" class="img-responsive"/>
            </li>
        {% endfor %}
    </ul>

    <h2 class="price">
        <span>R$</span>
        {% if real_estate.transacao == 'V' %}
            {{ real_estate.valor_venda|floatformat:"0"|intcomma }}
        {% elif real_estate.transacao == 'L' %}
            {{ real_estate.valor_aluguel|floatformat:"0"|intcomma }}
        {% endif %}
    </h2>

{#    Adicionar distancia #}

    <div class="logo" style="background-image: url(https://anunciantes.s3.amazonaws.com/avatar/788/logo.jpg)"></div>

    <p class="pull-left" style="margin-left: 10px;">Distancia: {{ real_estate.distance|distanceformat:2 }}</p>

    <ul class="list-unstyled list-inline caracteristicas col-lg-12 col-sm-12 col-xs-12 no-padding">
        <li><h3>Priv.</h3>{% firstof real_estate.area_privada|floatformat:"0"|intcomma '--' %}</li>
        <li><h3>Total</h3>{% firstof real_estate.area_total|floatformat:"0"|intcomma '--' %}</li>
        <li><h3>Quartos</h3>{% firstof real_estate.quartos '--' %}</li>
        <li><h3>Suites</h3>{% firstof real_estate.suites '--' %}</li>
        <li><h3>Vagas</h3>{% firstof real_estate.vagas '--' %}</li>
    </ul>
</a>